version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=ecommerce_cart_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres2024
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root2024
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
