version: "3.3"

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root2024
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
